### ISSUE TITLE
Afterware function runs twice

### ISSUE THREAD

**Issue by suneg** [the-road-to-learn-react/react-usereducer-middleware#1]
I've use this handy little utility on a project, but I've come across an issue where the afterware functions are called twice.

### Repro steps
1. Add the following code in the App function:
```
  const [test, setTest] = React.useState('test')

  React.useEffect(() => {
    console.log('todos changed')
    setTest(new Date())
  },[todos])
```
2. Run the app (npm start) and bring up the dev tools console
3. Click one of the check-boxes

Expected result:
```
logger before:
logger after:
todos changed
```

Actual result:
```
logger before:
logger after:
todos changed
logger after:
```
![Screenshot from 2021-03-22 19-19-16](https://user-images.githubusercontent.com/1258383/112038803-97284300-8b43-11eb-85f8-6a85c38920ac.png)

I'm unsure about the reason for it, but I've boiled it down to setting component state to an updated value, from an effect that relies on the state from the reducer. Clearly it does not make logical sense that the afterware would run more than once, or any other count than the middleware for that matter.

**Comment by rwieruch** [comment]
Can you check whether this change helps? I noticed this in my application as well, but forgot to update this repo here.

https://github.com/the-road-to-learn-react/react-usereducer-middleware/commit/39dd042182a060fd8d5732101a7aafa247652f5f

**Comment by suneg** [comment]
That seems to do the trick. I was experimenting with

`}, [afterwareFns.length, state]);`

instead of

`}, [afterwareFns, state]);`

Which also seems to work. But that might have some undesired side-effects.
